export const API_PERMISSIONS = {
  READ_BUDGET: "READ_BUDGET",
  WRITE_BUDGET: "WRITE_BUDGET",
  READ_USER: "READ_USER"
};

export const USER_ROLES = {
  STUDENT: "STUDENT",
  ADMIN: "ADMIN",
  TEACHER: "TEACHER",
  PARENT: "PARENT"
}
